#!/usr/bin/env node
/**
 * 🔍 EFRO Render Pre-Flight-Check
 * Prüft Node-Version, Config-Dateien, TGZ-Pakete und CSS-Abhängigkeiten
 * bevor der Build startet.
 */

import { execSync } from "child_process";
import { existsSync, writeFileSync, unlinkSync, readdirSync } from "fs";

console.log("🚦 EFRO Pre-Flight-Check gestartet ...");
console.log("🧩 Node-Version:", process.version);

//
// 1️⃣ Node-Version prüfen
//
const requiredMajor = 20;
const currentMajor = parseInt(process.version.split(".")[0].replace("v", ""), 10);
if (currentMajor !== requiredMajor) {
  console.warn(`⚠️  Node ${currentMajor}.x erkannt — erwartet wird ${requiredMajor}.x!`);
  console.warn("   Render wird zwar fortgesetzt, kann aber Warnungen zeigen.");
}

//
// 2️⃣ mascotbot-SDK prüfen
//
if (existsSync("./mascotbot-sdk-react-0.1.6.tgz")) {
  console.log("✅ mascotbot-SDK vorhanden");
} else {
  console.error("❌ mascotbot-SDK fehlt im Projekt-Root!");
  process.exitCode = 1;
}

//
// 3️⃣ PostCSS-Konfiguration prüfen
//
["postcss.config.js", "postcss.config.mjs"].forEach((file) => {
  if (existsSync(file)) {
    console.log(`⚙️  Entferne alte Datei: ${file}`);
    unlinkSync(file);
  }
});

if (!existsSync("postcss.config.cjs")) {
  console.log("🧩 Erstelle neue postcss.config.cjs ...");
  writeFileSync(
    "postcss.config.cjs",
    `// postcss.config.cjs (auto-generated by EFRO)
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`
  );
} else {
  console.log("✅ postcss.config.cjs vorhanden");
}

//
// 4️⃣ CSS-Abhängigkeiten prüfen
//
["tailwindcss", "postcss", "autoprefixer"].forEach((pkg) => {
  try {
    execSync(`npm list ${pkg}`, { stdio: "ignore" });
    console.log(`✅ ${pkg} installiert`);
  } catch {
    console.log(`🔧 Installiere ${pkg} ...`);
    execSync(`npm install -D ${pkg}`, { stdio: "inherit" });
  }
});

//
// 5️⃣ Übersicht ausgeben
//
console.log("----------------------------");
console.log("📂 Projekt-Root-Inhalt:");
for (const f of readdirSync(".")) console.log("  -", f);
console.log("----------------------------");
console.log("✅ Pre-Flight-Check abgeschlossen — bereit für Render-Build");
