import fs from "fs";
import path from "path";
import templates from "./scenarios/templates";

/**
 * Simple typo/noise generator: swaps two adjacent chars or removes one vowel.
 */
function addTypo(s: string): string {
  if (!s || s.length < 3) return s;
  // 50% swap adjacent, 50% remove vowel
  if (Math.random() < 0.5) {
    const i = Math.floor(Math.random() * (s.length - 1));
    const a = s.split("");
    const t = a[i];
    a[i] = a[i + 1];
    a[i + 1] = t;
    return a.join("");
  } else {
    const vowels = ["a", "e", "i", "o", "u", "ä", "ö", "ü"];
    const idx = [...s].findIndex((c) => vowels.includes(c.toLowerCase()));
    if (idx === -1) return s.slice(0, -1);
    return s.slice(0, idx) + s.slice(idx + 1);
  }
}

/**
 * Budget phrase application helpers
 */
function applyBudget(query: string, type: string, value: number, value2?: number): string {
  switch (type) {
    case "none":
      return query;
    case "max":
      return `${query} bis ${value} Euro`;
    case "between":
      return `${query} zwischen ${value} und ${value2 ?? Math.max(value + 50, value) } Euro`;
    case "around": {
      const lo = Math.max(1, Math.round(value * 0.9));
      const hi = Math.round(value * 1.1);
      return `${query} so um die ${value} Euro (ca. ${lo}-${hi} €)`;
    }
    default:
      return query;
  }
}

/**
 * Intent phrase application
 */
function applyIntent(query: string, intent: string): string {
  switch (intent) {
    case "bargain":
      return `${query} (günstig, billig)`;
    case "premium":
      return `${query} (Premium, hochwertig)`;
    case "compare":
      return `${query} (Vergleich, Unterschiede)`;
    default:
      return query;
  }
}

/**
 * Main generator
 */
function main() {
  const outPath = path.join(__dirname, "scenarios", "generated.ts");
  const budgets = ["none", "max", "between", "around"];
  const intents = ["bargain", "premium", "compare"];
  const budgetValues = [50, 100, 300, 700, 800]; // sample budget numbers used for phrases

  const generated: any[] = [];
  let idCounter = 1;

  if (!Array.isArray(templates)) {
    console.error("templates must export a default array in scripts/scenarios/templates.ts");
    process.exit(1);
  }

  for (const tpl of templates) {
    const baseQuery: string = tpl.query ?? tpl.q ?? tpl.text ?? "";
    const baseTitle: string = tpl.title ?? tpl.id ?? "scenario";

    for (const b of budgets) {
      for (const bv of budgetValues) {
        // for 'between' choose an upper value slightly above bv
        const betweenHigh = bv + Math.round(bv * 0.5) + 10;

        for (const intent of intents) {
          // two noise variants: original and typo
          for (let noise = 0; noise < 2; noise++) {
            let q = baseQuery;
            // apply budget phrase
            if (b === "between") {
              q = applyBudget(q, b, bv, betweenHigh);
            } else {
              q = applyBudget(q, b, bv);
            }
            // apply intent phrase
            q = applyIntent(q, intent);

            // apply noise
            if (noise === 1) q = addTypo(q);

            const id = `${tpl.id ?? baseTitle.replace(/\s+/g, "_")}_${idCounter++}`;

            const scenario = {
              id,
              title: `${baseTitle} [b:${b} v:${bv} i:${intent} n:${noise}]`,
              query: q,
              note: tpl.note ?? undefined,
              // carry through optional expectations from template if present
              expected: tpl.expected ?? undefined,
              context: tpl.context ?? undefined,
            };

            generated.push(scenario);
          }
        }
      }
    }
  }

  // write out generated file
  const fileContent =
    `// Auto-generated by scripts/gen-sellerbrain-scenarios.ts\n` +
    `// Do not edit by hand\n\n` +
    `export const generatedScenarios = ${JSON.stringify(generated, null, 2)} as const;\n`;

  fs.writeFileSync(outPath, fileContent, "utf8");
  console.log(`Wrote ${generated.length} scenarios to ${outPath}`);
}

main();
